
# Add '2022' to any change to 2022 project files
'2022':
  - any: ['summerofcode/2022.md', 'lfx-mentorship/2022/*', 'lfx-mentorship/2022/**/*']

# Add 'summer of code' label to any files in the Summer of Code project
'summer of code':
  - any: ['summerofcode/*', 'summerofcode/**/*']

# Add 'lfx mentorship' label to any files in the lfx mentorship project
'lfx mentorship':
  - any: ['lfx-mentorship/*', 'lfx-mentorship/**/*']

