#
# Add project labels
#

# Add 'summer of code' label to any files in the Summer of Code project
'summer of code':
  - summerofcode/*
  - summerofcode/**/*

# Add 'season of docs' label to any files in the season of docs project
'season of docs':
  - seasonofdocs/*
  - seasonofdocs/**/*

# Add 'lfx mentorship' label to any files in the lfx mentorship project
'lfx mentorship':
  - lfx-mentorship/*
  - lfx-mentorship/**/*

#
# Add date/term specific labels
#

# Add '2023' to any change to 2023 project files
2023:
  - summerofcode/2023.md
  - /seasonofdocs/README.md # TODO, update next cycle
  - lfx-mentorship/2023/*
  - lfx-mentorship/2023/**/*
  - TAGCS-Mentoring-WG/2023-meeting-minutes.md

# Add 'Term 1: March-May' label to files for that term
'Term 1: March-May':
  - /lfx-mentorship/2023/01-Mar-May/*
  - /lfx-mentorship/2023/01-Mar-May/**/*

# Add 'Term 2: June-Aug' label to files for that term
'Term 2: June-Aug':
  - /lfx-mentorship/2023/02-Jun-Aug/*
  - /lfx-mentorship/2023/02-Jun-Aug/**/*

# Add 'Term 3: Sept-Nov' label to files for that term
'Term 3: Sept-Nov':
  - /lfx-mentorship/2023/03-Sep-Nov/*
  - /lfx-mentorship/2023/03-Sep-Nov/**/*
