# cSpell:ignore textlintrc
# For settings, see
# https://www.streetsidesoftware.com/vscode-spell-checker/docs/configuration/
version: '0.2'
caseSensitive: true
#ignorePaths:
  # Temporary
  #  - /assessments/
# patterns:
#   - name: CodeBlock
#     pattern: |
#       /
#           ^(\s*[~`]{3,})   # code-block start
#           .*               # all languages and options, e.g. shell {hl_lines=[12]}
#           [\s\S]*?         # content
#           \1               # code-block end
#       /igmx # cspell:disable-line
# languageSettings:
#   - languageId: markdown
#     ignoreRegExpList:
#       - CodeBlock
words:
  - backstore
  - CNCF
  - Docsy
  - keda
  - kedacore
  - mentee
  - mentees
  - summerofcode
  - outreachy
  - techdocs
  - toto
