# cSpell:ignore textlintrc
# For settings, see
# https://www.streetsidesoftware.com/vscode-spell-checker/docs/configuration/
version: '0.2'
caseSensitive: false 
#ignorePaths:
  # Temporary
  #  - /assessments/
# patterns:
#   - name: CodeBlock
#     pattern: |
#       /
#           ^(\s*[~`]{3,})   # code-block start
#           .*               # all languages and options, e.g. shell {hl_lines=[12]}
#           [\s\S]*?         # content
#           \1               # code-block end
#       /igmx # cspell:disable-line
# languageSettings:
#   - languageId: markdown
#     ignoreRegExpList:
#       - CodeBlock
words:
- Aabid
- Aadhitya
- Aarush
- Abdelfatah
- Abdulrahman
- Abhinav
- Abhishek
- Abli
- Acharekar
- Acharya
- Achref
- actioning
- Adenekan
- Adil
- Aditi
- Aditya
- Affan
- Afroj
- Afzal
- Agarwal
- Ahuja
- Aidan
- Akash
- Akkoyun
- Akshat
- Akshay
- Alexandre
- Alexandrov
- Alhamdani
- aliok
- Almeida
- Alok
- alot
- Amal
- Amandeep
- Amarendiran
- Amaugo
- Amit
- Amye
- Anant
- André
- Andrzej
- Aniruddha
- Aniszczyk
- Ankita
- Ankur
- Anlan
- Ansari
- Ansh
- Antonette
- Antonin
- Antrea
- Anubhav
- Anurag
- Anusha
- Anushka
- Applicications
- Arah
- Arellano
- Aris
- Aritra
- Arkajyoti
- Asare
- Asen
- Ashish
- Ashok
- Ashutosh
- Asmit
- Asthana
- Atharva
- Aufart
- Avantika
- Ayman
- Ayush
- Azanul
- Azizi
- backstore
- Balagopal
- Bandarupalli
- Bansal
- Bartlomiej
- Bartłomiej
- Barun
- Barve
- Basak
- Bassey
- BATALE
- Batra
- behaviour
- behaviours
- BEHERA
- Berkus
- Bernal
- Bhalodyia
- Bhatia
- Bhattacharjee
- Bhokare
- Bhushan
- bincover
- bing
- Bingqi
- Bitergia
- Blando
- Boutselis
- Brétéché
- Brunell
- Bugwadia
- buildkit
- Buildpacks
- Bulani
- Bustamante
- Butley
- Calcote
- Calum
- CAPA
- CAPG
- CAPV
- Carrenho
- categorised
- centralised
- Chadha
- Chakraborty
- Chandan
- Changjiang
- Chao
- Chaoscenter
- Chatterjee
- Chaudhary
- checkin
- Chengwei
- Chien
- Chinmay
- Choudhary
- Clotributor
- cncf
- CNCF
- Configurator
- Crequy
- Crimlis
- Crossplane
- Cuadrado
- Cwen
- Cyrine
- daemonset
- Dahibhate
- Damilola
- Dandriyal
- Darach
- Dattatreya
- Davanum
- Debabrata
- Debopriya
- Deepesha
- Devfile
- Devrani
- Dezhi
- DHANUSH
- diandian
- Dilumika
- Diwakar
- Docsy
- Doğukan
- Edouard
- Elawady
- Elekto
- Emara
- Emphasise
- emphasising
- Eshaan
- evals
- Faeka
- Fahmy
- Faiz
- familiarise
- Faseela
- Filip
- finalised
- Florent
- folx
- FREEDISCH
- Gaikwad
- Gallaudet
- Gamoudi
- Gangal
- Gartia
- Gaurav
- Geetika
- Gelal
- Geng
- Giedrius
- Gies
- GLVS
- Gogoi
- Gondwal
- Goyal
- Grunert
- GSOC
- GSOD
- Guilherme
- Gurdasani
- Gurmannat
- hackmd
- Haiyu
- Hannon
- Haoyu
- Haque
- Hari
- Harikrishnan
- Harkirat
- Harshit
- Harshita
- Harshvir
- Hazra
- Hegde
- Heng
- Hirschberg
- Holleville
- Hongbing
- Hongcai
- Hrishav
- Hrushikesh
- Husni
- Hyokil
- Hyung
- Hygenic
- Ibegbu
- incentivise
- incentivised
- Inspektor
- Ishan
- Jadhav
- Jaiswal
- Jamdade
- Jatin
- Jerico
- Jiahuan
- Jianbai
- Jianbo
- Jiang
- Jiaojiao
- Jiehong
- Jingning
- João
- José
- Junyu
- Juraci
- KAAAs
- Kaiwalya
- Kakde
- Kammakomati
- Kanha
- Karanjot
- Karmada
- Karthik
- Kasbe
- Kata
- Katacoda
- kctrl
- Keadm
- keda
- kedacore
- keink
- Kemal
- Keqin
- Khaled
- Khare
- Khatri
- Khushi
- Kickstarted
- Kielty
- killercoda
- Kimmel
- Kiran
- Kiriti
- Kleinhans
- Knative
- Kontopoulos
- Konveyor
- Kornilios
- Kothiwal
- Kourtis
- Kowall
- Kröhling
- Krook
- Kruise
- Krzysztof
- Kubearmor
- Kubecon
- kubeedge
- Kubescape
- Kubevela
- Kubewarden
- Kudtarkar
- Kumar
- Kunal
- Kunkerkar
- Kunshuai
- Kushal
- Kushwaha
- Kuttl
- Kyverno
- Ladha
- leonardpahlke
- Leong
- Liang
- Liberti
- lifecycles
- Lijun
- Lingi
- Lingyu
- litmusctl
- littil
- Loriedo
- Łuczkiewicz
- Maggidi
- MAGNIM
- Mahesh
- maintainters
- Majumder
- Malakannawar
- Malik
- Manan
- Mangum
- Marek
- Mariam
- Marko
- Matei
- Matthis
- maximise
- maximising
- Meha
- Mehant
- Mehdi
- Mehta
- Meng
- mentee
- mentees
- menteeship
- mentorships
- Meshery
- Metard
- Michi
- Microshift
- Mingshan
- miniruby
- Mishra
- Mittal
- Mohanty
- Mohd
- Mohite
- Mondal
- Mudrinić
- Mukesh
- Mukherjee
- Mullan
- multiarch
- Muthuraj
- Mutkure
- Mutsuzaki
- Muvaffak
- Nagesh
- Nageshbansal
- Namkyu
- Nandle
- Natali
- Naveenraj
- Nawaz
- Nayak
- Nazare
- Neelanjan
- Neeraj
- negi
- Nicastro
- Nikhil
- Nikhita
- Nilisha
- Nishant
- Nishanth
- Nishchay
- Nithish
- Nitish
- NZST
- Obasi
- Okafor
- Olayinka
- Oluwatomi
- Omkar
- Ononiwu
- Onuş
- Openkruise
- opensource
- Operationalizing
- opps
- optimise
- optimised
- Optimising
- ORAS
- Organisational
- organise
- organised
- organises
- Orlin
- Oshi
- Otributor
- outreachy
- Paarth
- Paixão
- Panato
- Pandey
- Panigrahi
- Paolo
- Paranjpay
- Parashar
- Pareek
- Parthiba
- Parul
- Pathak
- Patierno
- Patil
- Pawar
- Pedraza
- Pengfei
- Petkovski
- Phong
- Piao
- Pierangelo
- Pilato
- Płotka
- Plubell
- poharkar
- Poinsard
- popoola
- Potpose
- Pourcelot
- Pradyumna
- PRAJJWAL
- Prakhar
- Pranav
- Prashant
- prateek
- Prathamesh
- Prayag
- prioritise
- prioritised
- Prodan
- promql
- Protasio
- Purohit
- Pushkar
- Qian
- Qiao
- Qing
- Qingguo
- Quan
- Quevedo
- QUIC
- Raghav
- Raghunath
- Raghuwanshi
- Rahul
- Rajawat
- Rajib
- Rakshit
- Rami
- Ratnaparkhi
- Rebecca
- recognised
- recognising
- Reddy
- Rego
- Rehman
- Reimagining
- Rejekts
- Renu
- reorganised
- Reto
- Riaan
- RISHABH
- Ritik
- Roald
- Rohan
- Rohit
- Roseline
- Roshan
- Rudraksh
- Ruhika
- Rupesh
- Rushikesh
- rustpython
- Ruturaj
- Ryans
- SAAD
- Sachin
- Sahil
- Sahoo
- Sahu
- Saikat
- SANCHITA
- Sandipan
- Sanjay
- Sanskar
- Sapkale
- Saranya
- Saraswat
- Sarthak
- Sascha
- Saswata
- Sathola
- Sathyaseelan
- Satyasi
- Savas
- Savsani
- Saxena
- Sayan
- Sched
- Schleich
- Sedef
- Senali
- Shadowtech
- Shaikh
- Shanware
- Sharma
- Shashank
- Shellea
- Shen
- Shentu
- Shepardson
- Shijing
- Shikhar
- Shinde
- Shivam
- Shiwei
- Shkuro
- Shonubi
- Shrotria
- Shuah
- Shuayb
- Shubham
- Shwet
- SIBASISH
- Siddharth
- Siddique
- Sigstore
- singh
- Sinha
- Siqi
- skillset
- skillsets
- SLSA
- Sofi
- Sohal
- Soham
- Sohan
- Songlin
- Soni
- Sood
- Soumik
- Soumil
- Soumya
- Spandan
- specialisations
- Srinivas
- Srushti
- Statkevičius
- Stavros
- Stencel
- Stocktake
- Strimzi
- struct
- Struthers
- STTS
- SUBHASISH
- Subhasmita
- Subhradeep
- subresources
- sudarsan
- Sudia
- summerofcode
- Sussman
- Swamy
- tada
- TAGCS
- Tarun
- Tathagata
- Tauranga
- Teber
- techdocs
- Tejas
- Tekton
- Tensorflow
- Teoh
- THIBAUT
- Thundiyil
- Tian
- Tianxiao
- TIANYI
- TIANYU
- Tiecheng
- Tihema
- Tiwari
- toto
- travelling
- Tributor
- Tsao
- Tushar
- Uche
- Umar
- unburying
- upskill
- Usman
- utilise
- Utuk
- Uwakmfon
- Uzair
- Vadim
- Vaibhav
- Vamsi
- Vansh
- Vanz
- Varma
- Vasilev
- Vásquez
- Vasu
- Vedant
- Venkat
- Verma
- Vijay
- Vikas
- Vishal
- Vitess
- Vlatko
- Vyankatesh
- Vyom
- Wahl
- waitlist
- wang
- WASI
- Wayfair
- Weijun
- Wertenteil
- Whanaungatanga
- Wilczynski
- william
- workstream
- workstreams
- Xiang
- xinity
- Xinyu
- Xuzheng
- Yadan
- YADAV
- Yarday
- Yash
- Yashwanth
- Yifei
- Yijie
- Yike
- Yiming
- Ying
- Yiying
- Youtube
- Yukun
- Yunkang
- Zager
- Zahid
- zefeng
- Zeng
- Zhang
- Zhao
- Zhen
- Zheng
- Zhiqiang
- ZHIYUAN
- Zhonghu
- Zhongpei
- Zhou
- Zhuoqi
- Zoller
- Zong
- Zuoning
